# Makefile for ChunkySting Tester
# 
# As usual, you can build this software by typing
#
#     make
#

# ----- Make Macros -----

CXXFLAGS    =	-g -stdlib=libc++ -std=c++11 -Wall -Wextra 
CXX	    =	clang++
TARGETS 	    =	Board solver sudoku-test
BOARD_OBJS     =	Board.o cell.o row.o square.o
SOLVER_OBJS    =    solver.o Board.o row.o square.o cell.o 
TEST_OBJS      =    sudoku-test.o testing-logger.o Board.o cell.o row.o square.o
ALL_OBJS	    =   $(BOARD_OBJS) $(SOLVER_OBJS) $(TEST_OBJS)

LIBS        =   -ldl -rdynamic -stdlib=libc++

# ----- Make Rules -----

all:	$(TARGETS)

test: sudoku-test
		./sudoku-test

solution: solver
		./solver

Board:	$(BOARD_OBJS)
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ -lpthread $(BOARD_OBJS) \
		$(LIBS)

solver: $(SOLVER_OBJS)
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o $@ -lpthread $(SOLVER_OBJS) \
		$(LIBS)

sudoku-test: $(TEST_OBJS)
	$(CXX) $(LDFLAGS) $(CXXFLAGS) -o sudoku-test $(TEST_OBJS) \
		$(LIBS)


clean:
	rm -f $(TARGETS) $(ALL_OBJS)

# ---- Dependencies (generated by typing ``clang++ -MM *.cpp'') ----

Board.o: Board.cpp Board.hpp
cell.o: cell.cpp cell.hpp
square.o: square.cpp square.hpp
row.o: row.cpp row.hpp
solver.o: solver.cpp Board.cpp Board.hpp 
sudoku-test.o: sudoku-test.cpp Board.hpp testing-logger.hpp
testing-logger.o: testing-logger.cpp testing-logger.hpp

